language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:qtrNisDJvfh5wDBQmSves9oP

services:
  - postgresql
  - docker

addons:
  postgresql: "10"

before_install:
  - npm install

install:
  - cp ./config/config.json.example ./config/config.json

before_script:
  - psql -U postgres -c "create extension postgis"
  - npm run db:create
  - npm run db:migrate
