language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:qtrNisDJvfh5wDBQmSves9oP

services:
  - postgresql
  - docker

env:
  - NODE_ENV=test

addons:
  postgresql: "9.6"

before_install:
  - npm install

install:
  - cp ./config/index.js.example ./config/index.js

script:
  - npm test
  - codecov
