language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:qtrNisDJvfh5wDBQmSves9oP

services:
  - postgresql
  - docker

env:
  - NODE_ENV=test

addons:
  postgresql: "9.6"

before_install:
  - npm install

install:
  - cp ./config/config.json.example ./config/config.json

before_script:
  - npm run db:create
  - npm run db:migrate
