language: node_js
node_js:
  - 'node'

notifications:
  slack: myaegee:qtrNisDJvfh5wDBQmSves9oP

services:
  - postgresql
  - docker

env:
  - NODE_ENV=test

addons:
  postgresql: "9.6"

before_install:
  - npm install

install:
  - cp ./config/index.js.example ./config/index.js

script:
  - npm audit
  - npm run lint
  - npm test
  - codecov

# after_script:
#   - sudo docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
#   - sudo docker tag aegee/oms-statutory aegee/oms-statutory:${TRAVIS_COMMIT}
#   - sudo docker push aegee/oms-statutory:${TRAVIS_COMMIT}
#   - sudo docker tag aegee/oms-statutory:${TRAVIS_COMMIT} aegee/oms-statutory:latest
#   - sudo docker push aegee/oms-statutory:latest
#   # if: branch = master
