orbs:
  slack: circleci/slack@3.4.2
  node: circleci/node@4.1.0
version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker run --name postgres -e POSTGRES_PASSWORD='5ecr3t' -p 5432:5432 -d postgres:13
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            which node && node -v
      - node/install-packages
      - run: mkdir -p ~/reports/jest
      - run:
          name: Run tests
          command: JEST_JUNIT_OUTPUT_DIR=$HOME/reports/jest npm test -- --reporters=default --reporters=jest-junit
      - run: ./node_modules/.bin/codecov
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build --no-cache statutory
  eslint:
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - node/install-packages
      - run: mkdir -p ~/reports
      - run: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  yamllint:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - run: pip install yamllint
      - run: yamllint -d .yamllint.yml .
  docker-build-and-push:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release
      - run: docker build  --tag aegee/statutory:$(node -p "require('./package.json').version") --tag aegee/statutory:latest -f docker/statutory/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/statutory:$(node -p "require('./package.json').version")
      - run: docker push aegee/statutory:latest
      - slack/status:
          success_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` with tags \`$(node -p "require('./package.json').version")\` and \`latest\` has been pushed to Dockerhub.
          failure_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` build and push has failed.

workflows:
  version: 2
  test:
    jobs:
      - test
  eslint:
    jobs:
      - eslint
  yamllint:
    jobs:
      - yamllint
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  docker-build-and-push:
    jobs:
      - docker-build-and-push
