version: "2.4"
### OMS STATUTORY     #######################################
services:
  oms-statutory:
    build:
      context: ./${PATH_OMS_STATUTORY}/..
      dockerfile: ./docker/oms-statutory/Dockerfile.dev
    image: aegee/oms-statutory:latest
    volumes:
      - ./${PATH_OMS_STATUTORY}/../:/usr/app/src
