version: "3.4"
### OMS STATUTORY     #######################################
services:
    postgres-oms-statutory:
        restart: always
        image: postgres:10
        volumes:
            - postgres-oms-statutory:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"

    oms-statutory:
        restart: always
        image: aegee/oms-statutory:latest
        volumes:
            - oms-statutory-media:/usr/app/media
            - shared:/usr/app/shared:ro
        depends_on:
            - postgres-oms-statutory
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_STATUTORY}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
            CORE_LOGIN: "${CORE_LOGIN}"
            CORE_PASSWORD: "${CORE_PASSWORD}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # cpu_count: 1
        # mem_limit: 900m
        labels:
            - "traefik.backend=oms-statutory"
            - "traefik.port=8084"
            - "traefik.frontend.rule=PathPrefix:/services/oms-statutory/api;PathPrefixStrip:/services/oms-statutory/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"
    oms-statutory-static:
        restart: on-failure
        image: aegee/nginx-static:latest
        volumes:
            - oms-statutory-media:/usr/app/media:ro
            - ./${PATH_OMS_STATUTORY}/oms-statutory-static/status.json:/usr/app/status.json:ro
            - ./${PATH_OMS_STATUTORY}/oms-statutory-static/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./${PATH_OMS_STATUTORY}/oms-statutory-static/sites/default:/etc/nginx/sites-available/default:ro
            - shared:/usr/app/shared:ro
        expose:
            - "80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.backend=oms-statutory-static"
            - "traefik.port=80"
            - "traefik.frontend.rule=PathPrefix:/media/statutory;PathPrefixStrip:/media/statutory"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

volumes:
    postgres-oms-statutory:
        driver: local
    oms-statutory-media:
        driver: local
    shared:
        driver: local

networks:
    default:
        external:
            name: OMS
