version: '3.2'
### OMS STATUTORY     #######################################
### mongodb Container #######################################
services:
    postgres-oms-statutory:
        restart: always
        image: postgres:10
        volumes:
            - postgres-oms-statutory:/var/lib/postgresql/data
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PW_POSTGRES}
    oms-statutory:
        restart: always
        build:
            context: ./$PATH_OMS_STATUTORY/oms-statutory
            dockerfile: ./Dockerfile.dev
        image: aegee/oms-statutory:dev
        volumes:
            - oms-statutory-media:/usr/app/media
            - ./$PATH_OMS_STATUTORY/../:/usr/app/src
            - shared:/usr/app/shared:ro
        links:
            - postgres-oms-statutory
        expose:
            - 8084
        environment:
            BUGSNAG_KEY: a7dfed96a71033eca7f4469e8f88878b
            PG_PASSWORD: ${PW_POSTGRES}
        labels:
            - "traefik.backend=oms-statutory"
            - "traefik.port=8084"
            - "traefik.frontend.rule=PathPrefix:/services/oms-statutory/api;PathPrefixStrip:/services/oms-statutory/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

volumes:
    postgres-oms-statutory:
        driver: "local"
    oms-statutory-media:
        driver: "local"
    shared:
        driver: "local"
